### ISSUE TITLE
Not working in Ubuntu

### ISSUE THREAD

**Issue by swetakedia** [orbitlens/stellar-notifier#13]
I am running the command npm i from root user in an ubuntu server and getting following error:
![image](https://user-images.githubusercontent.com/30261014/53710732-a22caf80-3e64-11e9-9368-04ec99c191fe.png)

**Comment by orbitlens** [comment]
Have you noticed 
> Error: EACCES: permission denied...

Looks like the OS user doesn't have enough privileges to create a directory.

All packages except the optional `ed25519` were installed. This package dependency is not critical and can be safely skipped. The app is ready for the launch.

**Comment by swetakedia** [comment]
@orbitlens Yes I did notice that. However I doubt because I am running the commands using root user.
